// src/App.tsx
import React, { useEffect } from 'react';
import Header from './components/Header';
import Banner from './sections/Banner';
import FeaturesSection from './sections/FeaturesSection';
import StatisticsSection from './sections/StatisticsSection';
import ServiceHistorySection from './sections/ServiceHistorySection';
import WorkflowSection from './sections/WorkflowSection';
import UseCasesSection from './sections/UseCasesSection';
import AI_Section from './sections/AI_Section';
import SupportSection from './sections/SupportSection';
import FAQSection from './sections/FAQSection';
import ContactSection from './sections/ContactSection';
import Footer from './sections/Footer';
import ScrollToTop from './components/ScrollToTop';
import CookieWidget from './components/CookieWidget';

function App() {
  useEffect(() => {
    document.title = "Support360 — Поддержка начинается с первого сообщения";
  }, []);

  return (
    <div className="font-sans">
      <Header />
      <Banner />
      <UseCasesSection />
      <FeaturesSection />
      <WorkflowSection />
      <StatisticsSection />
      <ServiceHistorySection />
      <AI_Section />
      <SupportSection />
      <FAQSection />
      <ContactSection />
      <Footer />
      <ScrollToTop />
      <CookieWidget />
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div class="font-sans">
    <AppHeader />
    <router-view />
    <AppFooter />
    <ScrollToTop />
    <CookieWidget />
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { useAppStore } from './stores/app'
import AppHeader from './components/AppHeader.vue'
import AppFooter from './components/AppFooter.vue'
import ScrollToTop from './components/ScrollToTop.vue'
import CookieWidget from './components/CookieWidget.vue'

const appStore = useAppStore()

const handleResize = () => {
  appStore.checkMobile()
}

onMounted(() => {
  document.title = "Support360 — Поддержка начинается с первого сообщения"
  appStore.checkMobile()
  window.addEventListener('resize', handleResize)
})

onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
})
</script>
