// src/components/FAQItem.tsx
import React, { useState } from 'react';

interface FAQItemProps {
  question: string;
  answer: string;
}

const FAQItem: React.FC<FAQItemProps> = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);
  
  return (
    <div className="border-b border-gray-200 last:border-b-0">
      <button
        className="flex justify-between items-center w-full py-4 text-left text-gray-800 hover:text-primary focus:outline-none transition-colors"
        onClick={() => setIsOpen(!isOpen)}
      >
        <span className="font-semibold">{question}</span>
        <svg
          className={`w-5 h-5 transform transition-transform ${isOpen ? 'rotate-180' : ''}`}
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <polyline points="6 9 12 15 18 9"></polyline>
        </svg>
      </button>
      <div className={`overflow-hidden transition-all duration-300 ${isOpen ? 'max-h-96 pb-4' : 'max-h-0'}`}>
        <p className="text-gray-600">{answer.split('\n').map((line, i) => (
            <React.Fragment key={i}>
              {line}
              <br />
            </React.Fragment>
          ))}</p>
      </div>
    </div>
  );
};

export default FAQItem;

// src/components/ui/FAQItem.vue
<template>
  <div class="border-b border-gray-200 last:border-b-0">
    <button
      @click="isOpen = !isOpen"
      class="flex justify-between items-center w-full py-4 text-left text-gray-800 hover:text-primary focus:outline-none transition-colors"
    >
      <span class="font-semibold">{{ question }}</span>
      <el-icon :class="['transform transition-transform', { 'rotate-180': isOpen }]">
        <ArrowDown />
      </el-icon>
    </button>
    <div :class="[
      'overflow-hidden transition-all duration-300',
      isOpen ? 'max-h-96 pb-4' : 'max-h-0'
    ]">
      <p class="text-gray-600">
        <span v-for="(line, i) in answer.split('\n')" :key="i">
          {{ line }}
          <br v-if="i < answer.split('\n').length - 1" />
        </span>
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ArrowDown } from '@element-plus/icons-vue'

interface Props {
  question: string
  answer: string
}

defineProps<Props>()

const isOpen = ref(false)
</script>
